package core_java.src.corejava.java_collections;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.TreeMap;

class Student {
    String name;
    int age;

    public Student(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAge(int age) {
        this.age = age;
    }
    // below two methods were generated by vscode

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + age;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true; // Identity check
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Student other = (Student) obj;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name)) // checks the values if not same
            return false;
        if (age != other.age)
            return false;
        return true; // if all ignore means same values
    }


}


public class MapDemo {
    public static void main(String[] args) {
        // Map is an interface in Java Collections but it DOES NOT extend the Collection interface.
        // It represents an object that maps keys to values.

        // Key Characteristics:
        // 1. A map cannot contain duplicate keys.
        // 2. Each key can map to at most one value. means key must be unique
        // 3. It's essentially a dictionary structure.

        // Common Implementations:
        // HashMap: Best performance, no guaranteed order.
        // LinkedHashMap: Maintains insertion order.
        // TreeMap: Maintains sorted order based on keys (Natural ordering).

        // --- HashMap ---
        // this stores the items in unordered format, means does not store order

        Map<Character, Integer> map = new HashMap<>();
        map.put('a', 1);
        map.put('b', 2);
        map.put('c', 3);

        int val = map.get('c');
        System.out.println("map[c]=" + val);

        map.forEach((key, value) -> System.out.println(key + "->" + value));
        for (Character key : map.keySet()) {
            System.out.println("Key: " + key + " Value: " + map.get(key));
        }
        boolean isPresent = map.containsKey('c');
        System.out.println("is c present:" + isPresent);
        System.out.println("is 2 present:" + map.containsValue(2));

        Set<Character> keys = map.keySet(); // it gives all the keys but in set format means unique

        map.remove('c');
        for (Character key : keys) {
            System.out.printf("map[%s]=%d\n", key, map.get(key));
        }



        // --- TreeMap ---
        // it gives the sorted values by keys
        // Treemap uses red black tree i.e self balanced binary search tree
        Map<Character, Integer> treeMap = new TreeMap<>();
        treeMap.put('c', 1);
        treeMap.put('a', 2);
        treeMap.put('b', 3);
        System.out.println("Using tree map to store ordered values");
        treeMap.forEach((key, value) -> System.out.println(key + "->" + value));

        Set<Entry<Character, Integer>> entries = treeMap.entrySet();
        System.out.println("entries=" + entries); // gives values in form of tuple or pair or we
                                                  // call Entry as a tuple in java
        for (Entry<Character, Integer> entry : entries) {
            System.out.printf("map[%s]=%d\n", entry.getKey(), entry.getValue());

        }

        // --- LinkedHashmap ---
        // stores the order of the value in which it was stored, it extends the hashmap and
        // implements the Map interface

        LinkedHashMap<String, Integer> linkedhashmap = new LinkedHashMap<>(); // Uses a
                                                                              // doubly-linked list
                                                                              // to remember
                                                                              // insertion.
        linkedhashmap.put("rony", 10);
        linkedhashmap.put("smith", 20);
        linkedhashmap.put("john", 11);


        linkedhashmap.forEach((key, value) -> System.out.println(key + "->" + value));
        // or
        for (var entry : linkedhashmap.entrySet()) {
            System.out.printf("map[%s]=%d\n", entry.getKey(), entry.getValue());
        }


        // Scenario we will create 3 objects of student class and two will have same values and map
        // will treat it as different unique keys
        Map<Student, Integer> studentMap = new HashMap<>(); // student marks map
        Student s1 = new Student("John", 19);
        Student s2 = new Student("Smith", 28);
        Student s3 = new Student("John", 19);
        System.out.println("hashcode of s1 and s3:" + s1.hashCode() + "->" + s3.hashCode()); // hashcode
                                                                                             // of
                                                                                             // s1
                                                                                             // and
                                                                                             // s3:589431969->1252169911
                                                                                             // (
                                                                                             // before
                                                                                             // fix)
                                                                                             // after
                                                                                             // fix:
                                                                                             // hashcode
                                                                                             // of
                                                                                             // s1
                                                                                             // and
                                                                                             // s2:71751689->71751689
        boolean isSameHashcode = s1.hashCode() == s3.hashCode();
        System.out.println(" hashcode of s1 == s3 :" + isSameHashcode); // before fix : false and
                                                                        // after fix: true

        studentMap.put(s1, 89);
        studentMap.put(s2, 78);
        studentMap.put(s3, 99);

        System.out.println("Size of student map:" + studentMap.size()); // it will show 3
        /**
         * But here the problem is why it is treating the same object values as different key?
         * Because when object is created, it gets a reference of memory location which points to
         * heap memory so in this case both will have different memory reference so map treats it
         * diff unique key
         * 
         * How map stores the values?
         * 
         * It has two thing - 1- Hashcode: It generate a unqiue hash code using hash function from
         * hash table and puts the values inside it if any collisons occur it used Red-black or self
         * balanced search binary tree to manage it. 2. equals: when we try to get the values first
         * it check whether we have same hashcode and then checks the values using equals
         * 
         * Contract b/w hashcode and equals: v.v.v. imp - If values of both objects using equals are
         * same , then hashcode must be also same otherwise it will violate the property of hashmap
         * 
         * e.g. s1.equals(s2) then s1.hashcode()== s2.hashcode() must be true
         * 
         * In our case it is not violating this case because both has different hashcode as both
         * points diff memory location but logically it should have size of map as 2 as we have s3
         * object same as s1 so values of s3 key must replace the latest values which has marks 99
         * 
         * 
         * Solution: - we will override the equals and hashcode methods of map and check the values
         * of the object whether both are same or not or
         * 
         * The Problem: Different memory addresses = Different buckets.
         * 
         * The Fix: Overriding hashCode and equals to use object fields.
         * 
         * The Result: Logical duplicates are handled as single keys.
         */

        System.out.println("Size after fix:" + studentMap.size());

    }
}
